[package]
name = "name-ld"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
name_const = { version = "0.1.0", path = "../name-const" }
