[package]
name = "name-debug-adapter"
version.workspace = true
edition.workspace = true
readme.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
serde = "1.0.218"
serde_json = "1.0.140"

[lints]
workspace = true
